### ISSUE TITLE
build isssue MINGW

### ISSUE THREAD

**Issue by michg** [LADSoft/OrangeC#5]
Hi,
thanks for you interesting compiler, especially the debug-possibility and the retargeting feature sounds very promising. I tried to build OrangeC under WINXP with MINGW GCC 4.7.2. The Compilation of the first cpp-File fails (restub.cpp): error invalid conversion from unsigned char* to std_basic_istream(char)::char_type*
in restub.cpp:41.
Probably you have used an older version of gcc for testing. Could you add the version number oft the compilers which have ben sucessfully used for building? Thanks.

**Comment by LADSoft** [comment]
Hi Michg,

I looked into this and yes I am working with MINGW gcc 4.8.1 for 
compiling.   I will add that and the other compiler versions into the 
documentation within the next couple of days.

However, while researching this I found that I did not lint the helper 
tools in the orangec\src directory the same as I linted the compiler, 
linker, etc... with various compilers.   So there were a handful of 
incompatibilities between the source files in this directory and mingw 
(also with openwatcom); there were actually problems with my build files 
that didn't cause them to be properly built and execute.   I have fixed 
the issues and checked the new files into GITHUB.

Thanks,

David


michg wrote:

**Comment by LADSoft** [comment]
Hi Michg,

By the way the retargeting isn't where I want it to be yet, while it is 
possible to retarget it as it stands I want to make it much easier to do 
so.   Good news is I hope to be done with C++ by the second quarter and 
retargeting is my highest priority after that :)   As far as the 
debugger goes I do have a working debugger for the C language but I 
should caution you that my IDE isn't exactly production ready as it 
still has a few issues sigh.   I will have to take more time to look at 
it again...

David


michg wrote:

**Comment by michg** [comment]
Hi David,
thanks for your update. It looks better now. I am getting much later an error at the GUI:
drawversion.c:92:5 unknown type name 'LVGROUP'.  Maybe a missing library?
I am interested in compilers for embedded processors like openrisc,lm32, riscv,..
The only support from compilers is here often only by gcc or llvm.  As they are very large
and change often, it is impossible (for me) to bring in own features.
At the moment I know only of very few retargetable compilers (LCC,..), and they rely on
other preprocessors, assembler, linkers. Therefore I like the idea of having a standalone, compact
toolset with debug support.  This seems to be the case for oangec. So I am really loooking forward to your further development.
Michael

**Comment by LADSoft** [comment]
Hi Michael,

LVGROUP is supposed to be defined in the WIN32 headers but is a 
relatively new feature, unfortunately MINGW doesn't support it 
natively.  OCIDE is supposed to define it anyway in RCGUI.H for 
compilers who don't natively support it, but the support relies on 
LVIF_GROUPID remaining undefined by the WIN32 headers.

Unfortunately MINGW does define LVIF_GROUPID under some circumstances; 
explicitly if _WIN32_WINNT is set to 0x501 or greater.   So I set 
_WIN32_WINNT to 0x500 to force the LVIF_GROUPID definition to not be 
made, then the OCIDE headers define LVGROUP and related things.  While 
not optimal, this solution is sufficient for the needs of OCIDE.

There are other windows related definitions I set on the command line, 
you can look in 'mingw.mak' to see them.

David

michg wrote:

**Comment by LADSoft** [comment]
Hi Michael,

Yes OrangeC is both standalone and compact - the sources you see in the 
source tree are all you need for an entire embedded tool chain, it can 
even build HEX and S19 images if you really want it to.   No elf/dwarf 
right now although that wouldn't be particularly difficult...

David


michg wrote:

**Comment by michg** [comment]
Hi David,
I checked the include-files of MINGW for LVIF_GROUPID. It is defined in comctrl.h. This leads to
the compilation error in drawversion.c  (#include <comctrl.h>). When I removed the defines in comtrl
the compilation continued, but stopped later with an error at lstree.c.
So I finally switched to OpenWatcom, with that I was able to build the GUI.
Michael

**Comment by LADSoft** [comment]
Hi Michael,

it should have built out of the box unless there is a disparity between 
the headers in the version of mingw you have and the one I have.    
Maybe tomorrow I will investigate this further....    But I'm glad you 
got it worked out.

David

michg wrote:

**Comment by LADSoft** [comment]
Hi Michael,

I tried downloading mingw 4.7.2 but am having problems with the mingw 
install program.   Right now it can't find the C++ compiler.   I have to 
move on to other issues temporarily but will probably try this again in 
a couple of days to see if I can figure it out.

Meanwhile, I did cross-check the build on mingw 4.8.1 and it worked fine.

David
michg wrote:

**Comment by LADSoft** [comment]
Hi Michael,

I got something that kinda sorta resembles MINGW4.7.2 installed, and it 
built OCIDE just fine out of the box.  However, OCIDE didn't run properly.

I cross-checked by compiling with MINGW.4.8.2 and then OCIDE ran properly.

While I was trying to get 4.7.2 installed I was reading a lot of horror 
stories people had about trying to install old versions of MINGW, and I 
am not at all convinced I've got a good install of 4.7.2 that has only 
4.7.2 files and nothing from other releases. Since it compiled OCIDE 
whereas you can't even compile it and since the compiled version doesn't 
run properly whereas compiling with the newer version of MINGW and with 
other compilers is fine, I can only imagine there must be a library 
mismatch somewhere. But it is beyond the scope of this project to try to 
diagnose the MINGW install packages.

At this point I'm going to have to drop this as an issue.

But I did update 'config.mak' to show version numbers of supported 
compilers.

David

michg wrote:
